-- ============================================================
-- PGL - Registro de impresiones de Gestiones de Entrega
-- ============================================================
-- Permite registrar primera impresión y reimpresiones de la
-- hoja de envío sin modificar el estado logístico de la GE.
-- ============================================================

ALTER TABLE public.gestiones_entrega
  ADD COLUMN IF NOT EXISTS fecha_primera_impresion timestamptz,
  ADD COLUMN IF NOT EXISTS fecha_ultima_impresion timestamptz,
  ADD COLUMN IF NOT EXISTS cantidad_impresiones integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ultima_impresion_por uuid;

ALTER TABLE public.gestiones_entrega
  DROP CONSTRAINT IF EXISTS gestiones_entrega_ultima_impresion_por_fkey;

ALTER TABLE public.gestiones_entrega
  ADD CONSTRAINT gestiones_entrega_ultima_impresion_por_fkey
  FOREIGN KEY (ultima_impresion_por)
  REFERENCES public.profiles(id);


-- ============================================================
-- Historial individual de impresiones
-- ============================================================

CREATE TABLE IF NOT EXISTS public.gestion_entrega_impresiones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gestion_entrega_id bigint NOT NULL
    REFERENCES public.gestiones_entrega(id),
  numero_impresion integer NOT NULL,
  impreso_por uuid NOT NULL
    REFERENCES public.profiles(id),
  fecha_impresion timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT gestion_entrega_impresiones_numero_check
    CHECK (numero_impresion > 0),

  CONSTRAINT gestion_entrega_impresiones_gestion_numero_key
    UNIQUE (gestion_entrega_id, numero_impresion)
);

CREATE INDEX IF NOT EXISTS
  gestion_entrega_impresiones_gestion_idx
ON public.gestion_entrega_impresiones (gestion_entrega_id);

CREATE INDEX IF NOT EXISTS
  gestion_entrega_impresiones_fecha_idx
ON public.gestion_entrega_impresiones (fecha_impresion);


-- ============================================================
-- RPC: registrar impresión / reimpresión
-- ============================================================

CREATE OR REPLACE FUNCTION public.registrar_impresion_gestion_entrega(
  p_gestion_entrega_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_usuario_id uuid;
  v_usuario_rol text;

  v_estado_actual text;
  v_numero_impresion integer;
  v_fecha_impresion timestamptz;
  v_operacion_id text;
BEGIN

  -- ----------------------------------------------------------
  -- Seguridad
  -- ----------------------------------------------------------

  v_usuario_id := auth.uid();

  IF v_usuario_id IS NULL THEN
    RAISE EXCEPTION
      'Debe existir un usuario autenticado para registrar una impresión';
  END IF;

  SELECT p.rol
  INTO v_usuario_rol
  FROM public.profiles p
  WHERE p.id = v_usuario_id
    AND p.activo = true;

  IF NOT FOUND THEN
    RAISE EXCEPTION
      'El usuario autenticado no existe o se encuentra inactivo';
  END IF;

  IF v_usuario_rol NOT IN ('ADMIN', 'SUPERVISOR', 'BBOO') THEN
    RAISE EXCEPTION
      'El usuario no posee permisos para imprimir Gestiones de Entrega';
  END IF;


  -- ----------------------------------------------------------
  -- Bloquear la GE durante el registro
  -- ----------------------------------------------------------

  SELECT
    ee.codigo,
    ge.operacion_id,
    ge.cantidad_impresiones
  INTO
    v_estado_actual,
    v_operacion_id,
    v_numero_impresion
  FROM public.gestiones_entrega ge
  JOIN public.estados_entrega ee
    ON ee.id = ge.estado_entrega_id
  WHERE ge.id = p_gestion_entrega_id
  FOR UPDATE OF ge;

  IF NOT FOUND THEN
    RAISE EXCEPTION
      'No existe la Gestión de Entrega %',
      p_gestion_entrega_id;
  END IF;


  -- ----------------------------------------------------------
  -- La hoja se imprime durante la preparación.
  -- No permitimos que esta RPC altere estados posteriores.
  -- ----------------------------------------------------------

  IF v_estado_actual <> 'EN_PREPARACION' THEN
    RAISE EXCEPTION
      'La Gestión de Entrega % se encuentra en estado % y no puede imprimirse desde esta etapa',
      p_gestion_entrega_id,
      v_estado_actual;
  END IF;


  -- ----------------------------------------------------------
  -- Registrar impresión
  -- ----------------------------------------------------------

  v_numero_impresion := COALESCE(v_numero_impresion, 0) + 1;
  v_fecha_impresion := now();

  INSERT INTO public.gestion_entrega_impresiones (
    gestion_entrega_id,
    numero_impresion,
    impreso_por,
    fecha_impresion
  )
  VALUES (
    p_gestion_entrega_id,
    v_numero_impresion,
    v_usuario_id,
    v_fecha_impresion
  );


  UPDATE public.gestiones_entrega
  SET
    fecha_primera_impresion =
      COALESCE(fecha_primera_impresion, v_fecha_impresion),
    fecha_ultima_impresion = v_fecha_impresion,
    cantidad_impresiones = v_numero_impresion,
    ultima_impresion_por = v_usuario_id,
    updated_by = v_usuario_id,
    updated_at = v_fecha_impresion
  WHERE id = p_gestion_entrega_id;


  -- ----------------------------------------------------------
  -- Resultado
  -- ----------------------------------------------------------

  RETURN jsonb_build_object(
    'ok', true,
    'gestion_entrega_id', p_gestion_entrega_id,
    'codigo_gestion',
      'GE-' || lpad(p_gestion_entrega_id::text, 8, '0'),
    'operacion_id', v_operacion_id,
    'estado', v_estado_actual,
    'numero_impresion', v_numero_impresion,
    'fecha_impresion', v_fecha_impresion
  );

END;
$function$;


REVOKE ALL
ON FUNCTION public.registrar_impresion_gestion_entrega(bigint)
FROM PUBLIC;

GRANT EXECUTE
ON FUNCTION public.registrar_impresion_gestion_entrega(bigint)
TO authenticated;

